### ISSUE TITLE
Duplicate S3 bucket

### ISSUE THREAD

**Issue by Pl4nky** [Sam-Martin/Ephemera#21]
Hello

If I try to deploy this, the resulting update stack has the bucket specified twice, resulting in the update failing and rolling back

ephemera-dev already exists in stack arn:aws:cloudformation:ap-southeast-2:1234567890:stack/serverless-ephemera-local-dev/afe64d03-eb45-4f1c-816d-133db9d5d4b8

 ```
   "S3Bucketephemeradev": {
      "Type": "AWS::S3::Bucket",
      "Properties": {
        "BucketName": "ephemera-dev",
        "NotificationConfiguration": {
          "LambdaConfigurations": [
            {
              "Event": "s3:ObjectRemoved:*",
              "Function": {
                "Fn::GetAtt": [
                  "EphemeraPopulateStaticSiteConfigLambdaFunction",
                  "Arn"
                ]
              }
            },
            {
              "Event": "s3:ObjectCreated:*",
              "Function": {
                "Fn::GetAtt": [
                  "EphemeraPopulateStaticSiteConfigLambdaFunction",
                  "Arn"
                ]
              },
              "Filter": {
                "S3Key": {
                  "Rules": [
                    {
                      "Name": "prefix",
                      "Value": "index.html"
                    }
                  ]
                }
              }
            }
          ]
        }
      },
      "DependsOn": [
        "EphemeraPopulateStaticSiteConfigLambdaPermissionephemeradevS3",
        "EphemeraPopulateStaticSiteConfigLambdaPermissionephemeradevS3"
      ]
    }

```
```
    "S3BucketPublicBucket": {
      "Type": "AWS::S3::Bucket",
      "Properties": {
        "WebsiteConfiguration": {
          "IndexDocument": "index.html",
          "ErrorDocument": "error.html"
        },
        "PublicAccessBlockConfiguration": {
          "RestrictPublicBuckets": true
        },
        "BucketName": "ephemera-dev"
      }
    },
```

I don't understand why as the serverless.yml only defines a single bucket.

**Comment by Pl4nky** [comment]
So it turns out 'existing: true' needs to be added to the EphemeraPopulateStaticSiteConfig events - else serverless will try and create it:

  ```
EphemeraPopulateStaticSiteConfig:
    handler: lambda/ephemera-populatestaticsiteconfig/ephemera-populatestaticsiteconfig.handler
    environment:
      BUCKET_NAME: ${self:custom.config.public_bucket_name}
      API_URL: !Join
        - ""
        -
          - https://
          - !Ref ApiGatewayRestApi
          - ".execute-api."
          - !Ref AWS::Region
          - ".amazonaws.com/"
          - ${self:custom.config.stage}
    events:
      - s3:
          bucket: ${self:custom.config.public_bucket_name}
          event: s3:ObjectRemoved:*
          existing: true
      - s3:
          bucket: ${self:custom.config.public_bucket_name}
          event: s3:ObjectCreated:*
          existing: true
          rules:
            - prefix: index.html
```

Fix found here: https://github.com/serverless/serverless/issues/6001
